// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo7ezL5P-ryYlek-4jC39ON-0hrhOJIsQ',
    appId: '1:25613462303:android:d24d6eedf4d765a18dde2a',
    messagingSenderId: '25613462303',
    projectId: 'nada-projects',
    storageBucket: 'nada-projects.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRVe52bQ5v9OQadVRrFy8Lv65LXsopN0Q',
    appId: '1:25613462303:ios:f24c3635daf658d58dde2a',
    messagingSenderId: '25613462303',
    projectId: 'nada-projects',
    storageBucket: 'nada-projects.appspot.com',
    androidClientId: '25613462303-6kp1vu9g6etefhkqf40fjmdaoaarqpmu.apps.googleusercontent.com',
    iosClientId: '25613462303-edb3v7a59a1lfm0nt9nsj0kq7bu81a7r.apps.googleusercontent.com',
    iosBundleId: 'com.nada.socialapp.socailApp',
  );
}
